version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install --save-dev serverless-offline
  pre_build:
    commands:
      - echo "Deploying to $ENVIRONMENT_NAME environment"
      - export STAGE=$ENVIRONMENT_NAME
  build:
    commands:
      - serverless deploy --stage $STAGE --verbose